[default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
  "@rari-capital/solmate=lib/solmate/src/",
  "@chiru-labs/erc721a=lib/ERC721A/",
  "@openzeppelin=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
